import { FileText } from 'lucide-react';
import Markdown from 'react-markdown';

const markdownContent = `
# Project Documentation: Green Neural Network (GNN)

## ABSTRACT

This document outlines the theoretical framework, instrumentation architecture, experimental methodology, and analytical models underlying the Green Neural Network (GNN), a distributed electrophysiological monitoring system designed to investigate bioelectrical activity in plant organisms.

The GNN framework captures low-amplitude electrical potentials generated within plant tissues and analyzes their temporal and spectral characteristics using signal processing and statistical correlation models. By deploying a network of botanical sensing nodes across multiple plant species, the system attempts to detect synchronous electrical responses and characterize plant electrophysiological behavior under controlled and natural environmental conditions.

The research builds upon early discoveries in plant electrophysiology by Jagadish Chandra Bose and integrates modern digital signal processing techniques to explore the possibility that plants exhibit coordinated electrical signaling networks that may represent complex environmental sensing mechanisms.

The long-term objective is to establish a scalable framework capable of decoding patterns within plant bioelectric signals and determining whether these signals contain meaningful physiological or ecological information.

---

# 1.0 Research Objectives & Hypothesis

The primary objective of the Green Neural Network project is to explore whether electrical signals generated by plants exhibit statistically significant patterns that reflect environmental interactions, physiological states, or potential cross-organism synchronization.

Plant cells generate electrical signals through ion flux across cellular membranes, particularly involving calcium, potassium, and chloride ions. These electrical signals propagate through plant vascular tissues such as the phloem and xylem.

The GNN project seeks to determine whether:

1. Electrical signals within individual plants correlate with environmental changes.
2. Plants of the same species exhibit consistent electrophysiological signatures.
3. Distributed plant networks demonstrate synchronous electrical responses under shared stimuli.
4. Signal propagation patterns resemble coordinated information transfer mechanisms.

The core hypothesis proposes that plant electrophysiological signals may exhibit **non-random temporal correlations**, suggesting the existence of complex signaling dynamics within botanical systems.

Additionally, the project investigates whether these signals could contribute to broader ecological sensing systems, potentially forming part of distributed biological networks within ecosystems.

---

# 2.0 Methodology & Instrumentation

## 2.1 Signal Acquisition

Electrical potentials are recorded using high-impedance silver/silver chloride (Ag/AgCl) electrodes attached to plant tissues, typically near the vascular bundle region. These electrodes detect minute voltage fluctuations generated by ionic transport across cell membranes.

Due to the extremely low amplitude of plant bioelectric signals, which typically range between microvolts and millivolts, specialized instrumentation is required.

The acquisition system includes:

* Differential instrumentation amplifiers
* Shielded signal cables
* Grounding systems to reduce environmental interference
* Analog filters to isolate relevant frequency bands

The instrumentation amplifier is configured with the following parameters:

* Gain: 1000×
* Common Mode Rejection Ratio (CMRR): greater than 100 dB
* Input impedance: greater than 10 GΩ

This configuration ensures that weak electrophysiological signals can be detected while minimizing common-mode noise from surrounding electronic devices.

---

## 2.2 Analog Signal Conditioning

Raw plant electrical signals are highly susceptible to environmental noise, particularly electromagnetic interference generated by power lines and electronic devices.

To mitigate these artifacts, the signal passes through a multi-stage filtering process.

A fourth-order Butterworth bandpass filter is applied with the following parameters:

* Lower cutoff frequency: 0.1 Hz
* Upper cutoff frequency: 100 Hz

This filtering stage removes slow baseline drift while preserving biologically relevant electrophysiological activity.

A notch filter centered at 50 Hz or 60 Hz may also be employed to suppress power-line interference.

---

## 2.3 Data Digitization

Following analog conditioning, signals are digitized using an analog-to-digital converter (ADC).

* Sampling rate: 20 Hz
* Resolution: 12-bit

These parameters were selected based on known frequency ranges of plant electrical signals, which typically occur in very low-frequency bands compared to animal neural activity.

Digitized signals are transmitted to a central processing unit where they are stored for real-time and offline analysis.

---

# 3.0 Data Processing & Signal Analysis

## 3.1 Spectral Analysis

To analyze the frequency characteristics of plant electrical signals, the system applies Fast Fourier Transform (FFT) analysis.

FFT converts time-domain signals into the frequency domain, allowing identification of dominant oscillatory components.

Spectral analysis allows researchers to determine whether certain plant species exhibit characteristic frequency signatures or whether environmental events produce distinct spectral patterns.

---

## 3.2 Signal Energy Estimation

Signal strength is quantified using Root Mean Square (RMS) amplitude measurements.

RMS analysis provides a robust method for estimating signal energy over time and detecting fluctuations associated with environmental stimuli or physiological stress.

RMS amplitude variations may correlate with plant hydration status, temperature changes, or mechanical stimulation.

---

## 3.3 Predictive Filtering

To model expected signal behavior and detect anomalies, the system implements a Kalman filtering algorithm.

The Kalman filter estimates the probable future state of a signal based on prior observations while accounting for measurement uncertainty.

If the measured signal deviates significantly from predicted behavior, the system flags the event as a potential physiological anomaly.

This allows the detection of subtle electrophysiological responses that may otherwise be overlooked.

---

# 4.0 Theoretical Framework

The Green Neural Network research draws upon several foundational concepts in plant physiology and systems biology.

## 4.1 Plant Electrophysiology

Plants generate electrical signals through the movement of ions across membranes in response to stimuli such as light, mechanical disturbance, or chemical exposure.

These signals propagate through plant tissues as:

* Action Potentials (AP)
* Variation Potentials (VP)

Action potentials occur rapidly and resemble neural spikes in animals, whereas variation potentials propagate more slowly and are often associated with physical damage or stress responses.

---

## 4.2 Systemic Acquired Resistance (SAR)

Plants possess complex defense mechanisms that allow them to respond to localized stress by activating immune responses throughout the organism.

This process, known as Systemic Acquired Resistance, involves chemical signaling pathways and electrical propagation through vascular tissues.

Tracking electrical signal propagation speed may provide insight into whether electrical signaling complements or precedes chemical signaling mechanisms.

---

## 4.3 The Plant Electrome

The term "electrome" refers to the complete electrical signaling activity occurring within a plant.

Mapping the electrome may reveal species-specific patterns of electrophysiological activity and provide insights into plant-environment interactions.

Understanding the electrome could allow researchers to develop non-invasive monitoring systems for plant health and environmental stress detection.

---

# 5.0 Network Architecture & Correlation Engine

The Green Neural Network utilizes a distributed mesh architecture in which each plant acts as an independent sensing node.

Each node continuously streams electrophysiological data to a central processing system responsible for correlation analysis.

To identify synchronous electrical behavior across multiple plants, the system computes the Pearson correlation coefficient between signal pairs.

High correlation values indicate simultaneous signal fluctuations between plant nodes.

Events are classified as **Neural Sync Events** when the following conditions are met:

* Correlation coefficient greater than 0.85
* Synchronization duration greater than 2000 milliseconds

These events may indicate shared responses to environmental stimuli or other underlying physiological mechanisms.

---

# 6.0 Potential Applications

The Green Neural Network may enable several practical applications:

* Early plant stress detection in agriculture
* Precision irrigation systems
* Environmental monitoring
* Plant health diagnostics
* Biological sensing networks

Because plants naturally detect environmental parameters such as humidity, chemical compounds, and atmospheric changes, they may serve as highly sensitive biosensors.

---

# 7.0 Limitations of Current Research

Despite promising theoretical foundations, several limitations must be acknowledged.

Plant electrical signals are extremely weak and easily influenced by external noise sources. Environmental variables must therefore be carefully controlled during experiments.

Furthermore, electrophysiological signals do not necessarily imply cognitive or emotional processes within plants. Current research interprets these signals as physiological responses rather than indicators of consciousness.

Future work must therefore emphasize rigorous statistical validation and reproducibility.

---

# 8.0 Future Research Directions

Several avenues for future exploration exist within the GNN framework.

## 8.1 Machine Learning Signal Classification

Advanced machine learning models may be trained to identify patterns within plant electrophysiological signals.

Neural networks could potentially classify plant states such as:

* hydration stress
* pathogen exposure
* temperature stress
* nutrient deficiency

---

## 8.2 Long-Term Electrome Mapping

Continuous monitoring over extended time periods may reveal circadian electrical rhythms within plants.

These rhythms could provide insight into plant metabolic cycles and environmental adaptation.

---

## 8.3 Multi-Species Signal Networks

Future experiments may involve large-scale plant networks containing dozens or hundreds of nodes.

Cross-species comparisons could reveal whether certain plant species exhibit stronger electrophysiological responsiveness.

---

## 8.4 Integration with Environmental Sensors

Combining plant bioelectric monitoring with external environmental sensors could enable causal modeling between environmental events and plant electrical responses.

Such systems could provide valuable tools for ecological monitoring and climate research.

---

## 8.5 Bio-Computational Interfaces

A speculative but intriguing direction involves exploring whether plant electrical signals could be integrated into hybrid biological-computational systems.

Such systems could theoretically allow plants to function as biological sensing networks within cyber-physical environments.

---

# 9.0 Mathematical Modeling of Plant Signal Propagation

Plant electrophysiological signaling can be modeled using diffusion-based and wave-propagation frameworks similar to those used in neural electrophysiology. Electrical potentials generated by ion exchange across plant cell membranes propagate through vascular tissues such as the phloem.

In the Green Neural Network framework, the electrical potential recorded from a plant node can be represented as a time-dependent signal:

\`V(t)\`

where \`V(t)\` represents the measured electrical potential at time \`t\`.

The energy of the signal over a time interval can be approximated using the root mean square (RMS) formulation:

\`V_RMS = sqrt((1/T) * integral_0^T V(t)^2 dt)\`

This formulation provides a measure of signal strength independent of polarity fluctuations.

Signal propagation between plant nodes may be approximated using a simplified diffusion-wave equation:

\`∂V/∂t = D ∇²V - λV + S(t)\`

Where:

* \`D\` represents the effective conductivity coefficient of plant tissue
* \`∇²V\` represents spatial diffusion of electrical potential
* \`λ\` represents signal attenuation
* \`S(t)\` represents external stimulus inputs

This model allows estimation of signal propagation velocity and attenuation within plant tissue.

Such modeling may allow future studies to compare electrophysiological propagation speeds with known biochemical signaling pathways.

---

# 10.0 Experimental Protocol and Reproducibility Framework

To ensure experimental validity and reproducibility, the Green Neural Network system follows a standardized experimental protocol.

## 10.1 Environmental Control

Experiments are conducted under controlled environmental conditions to reduce confounding variables.

Environmental parameters recorded include:

* Ambient temperature
* Relative humidity
* Light intensity
* Soil moisture
* Atmospheric pressure

Environmental monitoring allows correlation analysis between plant electrical responses and external conditions.

---

## 10.2 Baseline Calibration

Before applying experimental stimuli, each plant node undergoes a baseline calibration period lasting 24–48 hours.

During this phase:

* Continuous electrical signals are recorded
* Baseline voltage variance is calculated
* Natural circadian signal patterns are identified

This baseline establishes reference thresholds for anomaly detection.

---

## 10.3 Stimulus Testing

Controlled stimuli are introduced sequentially to evaluate plant electrophysiological responses.

Stimuli categories include:

* **Mechanical Stimulus**: Touch or vibration applied to plant tissue.
* **Hydrological Stimulus**: Water introduced to the soil after controlled dehydration periods.
* **Photonic Stimulus**: Changes in light intensity or wavelength exposure.
* **Thermal Stimulus**: Gradual temperature variations applied within safe biological ranges.

Each stimulus event is timestamped and logged to correlate signal responses with external triggers.

---

## 10.4 Multi-Species Comparative Trials

The Green Neural Network incorporates multiple plant species to evaluate species-specific electrophysiological signatures.

Example species set:

* Ficus elastica
* Epipremnum aureum
* Aloe vera
* Ocimum basilicum

Cross-species comparison allows researchers to determine whether electrophysiological responses are conserved across botanical families or specific to certain plant types.

---

# 11.0 Statistical Validation & Signal Correlation

Given the inherently noisy nature of biological electrical signals, rigorous statistical validation is necessary to ensure that observed patterns are not artifacts of random fluctuations.

## 11.1 Cross-Correlation Analysis

The similarity between two plant signals is measured using the Pearson correlation coefficient:

\`r = sum((Xi - Xbar)(Yi - Ybar)) / sqrt(sum((Xi - Xbar)^2) * sum((Yi - Ybar)^2))\`

Where:

* \`Xi\` and \`Yi\` represent voltage measurements from two plant nodes
* \`Xbar\` and \`Ybar\` represent mean signal values

Values of \`r\` close to +1 indicate strong positive synchronization between nodes.

---

## 11.2 Statistical Significance Testing

To determine whether observed correlations are statistically meaningful, hypothesis testing procedures are applied.

* **Null hypothesis**: Observed synchronization events occur due to random noise.
* **Alternative hypothesis**: Synchronization events reflect genuine electrophysiological responses shared between plant nodes.

Significance is evaluated using p-values derived from correlation distributions over large datasets.

---

## 11.3 Signal Entropy Analysis

Shannon entropy is used to quantify signal complexity within plant electrophysiological recordings.

High entropy values indicate complex and unpredictable signals, whereas low entropy may indicate stable physiological states.

Entropy analysis may help determine whether plant signals contain structured information rather than random noise.

---

# 12.0 Ethical and Scientific Considerations

Although plants lack nervous systems comparable to animals, they exhibit complex biochemical and electrophysiological signaling mechanisms.

Interpretations of plant electrical activity must therefore remain grounded in established plant physiology rather than anthropomorphic assumptions.

The Green Neural Network project emphasizes:

* empirical observation
* reproducible experimentation
* statistical validation

Speculative interpretations regarding plant cognition or communication remain areas for future research and must be approached cautiously.

---

# 13.0 Long-Term Vision

The Green Neural Network represents an early-stage exploration into plant electrophysiological networks.

If scalable monitoring systems can reliably decode plant electrical signals, future applications may include:

* planetary-scale environmental monitoring networks
* bio-integrated sensing systems
* precision agriculture optimization
* ecological early warning systems for drought or pathogen outbreaks

Ultimately, the project aims to contribute to a deeper understanding of plant-environment interactions and the hidden electrical dynamics that govern biological systems.

---

### Feature Prompt: Bio-Hybrid Language Interface (BHLI)

Add a new module to the **Green Neural Network (GNN)** architecture called **Bio-Hybrid Language Interface (BHLI)**. This subsystem explores the integration of plant electrophysiological signals with large language model token generation to create a bio-cybernetic computational loop.

The objective of this module is to investigate whether stochastic biological signals derived from plant electrophysiology can be used as dynamic entropy sources that influence probabilistic token selection within an AI language model.

Unlike neural systems such as those used in the CL1 developed by Cortical Labs, which utilize living neurons as computational substrates, the Green Neural Network explores a plant-based electrophysiological interface as a passive biological signal generator.

---

### System Architecture

The Bio-Hybrid Language Interface operates through a five-layer processing pipeline:

* Plant Electrophysiological Node Layer
* Signal Conditioning Layer
* Feature Extraction Layer
* Token Probability Modulation Layer
* Language Model Output Layer

Each plant node produces continuous electrical potential fluctuations. These signals are collected and normalized before being translated into statistical features that influence token probability distributions within the language model.

---

### Signal Integration Process

1. **Plant Signal Acquisition**

Electrical signals are captured from plant nodes through Ag/AgCl electrodes attached to vascular tissues.

Typical signal range:

0.1 mV – 10 mV

Signals are sampled continuously and streamed into the processing engine.

---

2. **Signal Normalization**

Raw signals are normalized to a bounded range to prevent instability in downstream models.

Example transformation:

\`\`\`
NormalizedSignal = (V - Vmin) / (Vmax - Vmin)
\`\`\`

---

3. **Feature Extraction**

Multiple signal features are extracted in real time:

* RMS amplitude
* Spectral entropy
* Dominant frequency
* Temporal variance
* Signal correlation across plant nodes

These features form a biological feature vector representing the instantaneous electrophysiological state of the plant network.

---

4. **Token Probability Modulation**

The biological feature vector is used to influence token selection probabilities in the language model.

Let

\`\`\`
P_base(token)
\`\`\`

represent the original token probability produced by the LLM.

A biological modulation factor is applied:

\`\`\`
P_modified(token) = P_base(token) × W_bio
\`\`\`

Where **W_bio** is derived from plant signal features.

This allows plant electrophysiology to function as a dynamic bias layer that subtly alters the generative output of the model.

---

### Bio-Cybernetic Feedback Loop

An experimental feedback loop can also be implemented.

1. The language model generates text.
2. Generated output triggers environmental stimuli.
3. Plants respond with altered electrical activity.
4. These signals influence future token generation.

This establishes a closed-loop interaction between biological systems and artificial intelligence.

---

### Experimental Goals

The Bio-Hybrid Language Interface aims to investigate:

* whether plant electrophysiological signals can serve as biologically derived randomness sources
* whether multi-plant networks exhibit correlated signal states that influence AI output patterns
* whether long-term plant signal patterns produce measurable shifts in AI generative behavior

---

### Potential Applications

* Bio-hybrid computational interfaces
* Biological entropy generators for AI systems
* Experimental bio-AI interaction models
* Environmental data-driven language generation
* Bio-signal augmented AI creativity models

---

### Future Research Direction

Future versions of the system may incorporate adaptive machine learning layers that learn correlations between plant electrophysiological states and AI output patterns.

Long-term experimentation could explore whether plant networks develop stable electrophysiological signatures that influence generative AI behavior in predictable ways.

---
`;

export function DocumentationView() {
  return (
    <div className="glass-panel rounded-xl p-10 max-w-7xl mx-auto">
      <div className="prose prose-invert prose-emerald max-w-none prose-h1:text-[#00FF88] prose-h2:text-white prose-h3:text-zinc-300 prose-a:text-[#00FF88] prose-strong:text-white prose-code:text-[#00FF88] prose-code:bg-[#00FF88]/10 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded-md prose-code:before:content-none prose-code:after:content-none">
        <Markdown>{markdownContent}</Markdown>
      </div>
      
      {/* Footer */}
      <div className="pt-12 mt-12 border-t border-white/10 text-center">
        <p className="font-mono text-xs text-zinc-600">
          CONFIDENTIAL RESEARCH DATA • GNN PROJECT • DO NOT DISTRIBUTE • REVISION 2.4.1
        </p>
      </div>
    </div>
  );
}
